#!/usr/bin/env python3
"""Render all three languages from one reviewed condition catalogue."""
import json
from pathlib import Path
from html import escape as e
R=Path(__file__).resolve().parents[1]
D=json.loads((R/'content/conditions.json').read_text())
by={x['slug']:x for x in D}
L={
'hy': dict(home='Գլխավոր',about='Մեր մասին',conditions='Ցավային վիճակներ',booking='Գրանցվել այցի',patient='Պացիենտի մուտք',symptoms='Ինչ կարող եք զգալ',assessment='Ինչպես է գնահատվում',care='Բուժման մոտեցումներ',urgent='Երբ դիմել անհետաձգելի օգնության',related='Առնչվող թեմաներ',note='Կարևոր է իմանալ',read='Լրացուցիչ ընթերցում',disclaimer='Տեղեկատվությունը կրթական է և չի փոխարինում անհատական բժշկական գնահատմանը։ Ախտանշանների նմանությունը ինքնուրույն ախտորոշման հիմք չէ։',search='Փնտրել ցավային վիճակ',all='Բոլորը',intro='Գտեք համապատասխան թեման ըստ տեղակայման կամ ցավի տեսակի։ Յուրաքանչյուր էջում՝ բնորոշ նշաններ, գնահատում, բուժման մոտեցումներ և ուշադրություն պահանջող իրավիճակներ։',empty='Համապատասխան թեմա չի գտնվել։',address='Պուշկին 56/1, Երևան',toc='Այս էջում',image='Թեմատիկ պատկեր',caption='Պատկերը թեմատիկ նկարազարդում է։',contact='Կապ և այցի գրանցում'),
'en': dict(home='Home',about='About us',conditions='Pain conditions',booking='Book a visit',patient='Patient access',symptoms='What you may feel',assessment='How it is assessed',care='Approaches to care',urgent='When to seek urgent help',related='Related topics',note='Good to know',read='Further reading',disclaimer='This is educational information and does not replace an individual medical assessment. Similar symptoms alone do not establish a diagnosis.',search='Search pain conditions',all='All topics',intro='Find a topic by location or type of pain. Each page explains typical symptoms, assessment, approaches to care and situations needing prompt attention.',empty='No matching topics found.',address='56/1 Pushkin Street, Yerevan',toc='On this page',image='Illustrative image',caption='Image used as a thematic illustration.',contact='Contact and appointments'),
'ru': dict(home='Главная',about='О нас',conditions='Болевые состояния',booking='Записаться на приём',patient='Вход для пациентов',symptoms='Что вы можете ощущать',assessment='Как проводят оценку',care='Подходы к лечению',urgent='Когда нужна срочная помощь',related='Связанные темы',note='Полезно знать',read='Дополнительная информация',disclaimer='Это образовательная информация, которая не заменяет индивидуальную медицинскую оценку. Сходство симптомов само по себе не устанавливает диагноз.',search='Поиск болевого состояния',all='Все темы',intro='Найдите тему по локализации или типу боли. На каждой странице: характерные симптомы, оценка, подходы к лечению и ситуации, требующие быстрого обращения.',empty='Подходящих тем не найдено.',address='Пушкина 56/1, Ереван',toc='На этой странице',image='Тематическое изображение',caption='Изображение используется как тематическая иллюстрация.',contact='Контакты и запись')}
GROUPS={
'spine':['Спина и шея','Մեջք և պարանոց','Back and neck'],
'head':['Голова и лицо','Գլուխ և դեմք','Head and face'],
'upper':['Плечо, локоть и кисть','Ուս, արմունկ և ձեռք','Shoulder, elbow and hand'],
'lower':['Тазобедренная область, колено и стопа','Կոնք, ծունկ և ոտնաթաթ','Hip, knee and foot'],
'nerve':['Нервная боль','Նյարդային ցավ','Nerve pain'],
'recovery':['После травмы или операции','Վնասվածքից կամ վիրահատությունից հետո','After injury or surgery']}
def group(g,l): return GROUPS[g][{'ru':0,'hy':1,'en':2}[l]]
WARN={
'spine': ['Նոր միզարձակման կամ կղազատման խանգարումը, շեքի թմրածությունը, արագ աճող թուլությունը կամ ծանր վնասվածքից հետո ցավը պահանջում են անհետաձգելի գնահատում։','New bladder or bowel problems, numbness around the saddle area, rapidly increasing weakness or pain after major trauma need immediate assessment.','Новые нарушения мочеиспускания или дефекации, онемение промежности, быстро нарастающая слабость или боль после серьёзной травмы требуют немедленной оценки.'],
'head':['Հանկարծակի սկսված անսովոր ուժեղ գլխացավը, նոր խոսքի կամ տեսողության խանգարումը, թուլությունը, գիտակցության փոփոխությունը կամ ջերմությամբ պարանոցի կոշտությունը պահանջում են շտապ օգնություն։','A sudden unusually severe headache, new speech or vision problems, weakness, altered consciousness, or a stiff neck with fever need emergency care.','Внезапная необычно сильная головная боль, новые нарушения речи или зрения, слабость, изменение сознания или скованность шеи с лихорадкой требуют экстренной помощи.'],
'upper':['Ծանր վնասվածքը, ձևափոխված հոդը, ձեռքի հանկարծակի ուժի կորուստը կամ տաք ու կարմիր հոդը՝ ջերմությամբ, պահանջում են արագ բժշկական գնահատում։','Major injury, a deformed joint, sudden loss of arm strength, or a hot red joint with fever need prompt medical assessment.','Серьёзная травма, деформация сустава, внезапная потеря силы руки или горячий красный сустав с лихорадкой требуют быстрой медицинской оценки.'],
'lower':['Ոտքին հենվելու անկարողությունը վնասվածքից հետո, տաք ու կարմիր հոդը՝ ջերմությամբ, կամ հանկարծակի սառը ու գունատ ոտքը պահանջում են անհետաձգելի գնահատում։','Inability to bear weight after injury, a hot red joint with fever, or a suddenly cold pale foot need urgent assessment.','Невозможность опереться на ногу после травмы, горячий красный сустав с лихорадкой или внезапно холодная бледная стопа требуют срочной оценки.'],
'nerve':['Հանկարծակի կամ արագ աճող թուլությունը, զգացողության կտրուկ կորուստը կամ նոր միզարձակման ու կղազատման խանգարումը պահանջում են անհետաձգելի գնահատում։','Sudden or rapidly increasing weakness, abrupt loss of sensation or new bladder or bowel problems need immediate assessment.','Внезапная или быстро нарастающая слабость, резкая потеря чувствительности или новые нарушения мочеиспускания и дефекации требуют немедленной оценки.'],
'recovery':['Վերքի կարմրությունը կամ արտահոսքը, ջերմությունը, արագ ուժեղացող ցավը կամ նոր թուլությունը պետք է արագ գնահատել։ Հանկարծակի շնչահեղձության կամ կրծքային ցավի դեպքում դիմեք շտապ օգնության։','Wound redness or discharge, fever, rapidly worsening pain or new weakness need prompt assessment. Sudden breathlessness or chest pain requires emergency care.','Покраснение или выделения из раны, лихорадка, быстро усиливающаяся боль или новая слабость требуют быстрой оценки. При внезапной одышке или боли в груди нужна экстренная помощь.']}
SOURCES={
'back-pain':'https://www.nhs.uk/conditions/back-pain/', 'neck-pain':'https://www.nhs.uk/symptoms/neck-pain-and-stiff-neck/', 'sciatica':'https://www.nhs.uk/conditions/sciatica/', 'headache':'https://www.nhs.uk/symptoms/headaches/', 'shoulder-pain':'https://www.nhs.uk/symptoms/shoulder-pain/', 'knee-pain':'https://www.nhs.uk/symptoms/knee-pain/', 'hip-pain':'https://www.nhs.uk/symptoms/hip-pain/', 'heel-pain':'https://www.nhs.uk/symptoms/foot-pain/heel-pain/', 'plantar-fasciitis':'https://www.nhs.uk/conditions/plantar-fasciitis/', 'carpal-tunnel':'https://www.nhs.uk/conditions/carpal-tunnel-syndrome/', 'crps':'https://www.nhs.uk/conditions/complex-regional-pain-syndrome/', 'pudendal-neuralgia':'https://www.nhs.uk/conditions/pudendal-neuralgia/', 'postherpetic-neuralgia':'https://www.nhs.uk/conditions/post-herpetic-neuralgia/', 'trigeminal-neuralgia':'https://www.nhs.uk/conditions/trigeminal-neuralgia/', 'mortons-neuroma':'https://www.nhs.uk/conditions/mortons-neuroma/', 'gluteal-tendinopathy':'https://www.cuh.nhs.uk/patient-information/gluteal-tendinopathy/', 'persistent-facial-pain':'https://www.uclh.nhs.uk/patients-and-visitors/patient-information-pages/persistent-idiopathic-facial-pain/'}
for s in ['post-amputation-pain','phantom-limb-pain','residual-limb-pain']: SOURCES[s]='https://www.nhs.uk/tests-and-treatments/amputation/'
for s in ['peripheral-neuropathic-pain','diabetic-neuropathic-pain','neuropathic-pain']: SOURCES[s]='https://www.nhs.uk/conditions/peripheral-neuropathy/'
def link(slug,l,label=None): return f'<a href="{slug}-{l}.html">{e(label or by[slug]["title"][l])}</a>'
def shell(slug,l,title,description,body):
 t=L[l];home='hy.html' if l=='hy' else f'{l}.html'
 languages=''.join(f'<a href="{slug}-{other}.html" lang="{other}" hreflang="{other}"'+(' aria-current="page"' if l==other else '')+f'>{other.upper()}</a>' for other in L)
 alternates=''.join(f'<link rel="alternate" hreflang="{other}" href="https://painclinic.am/{slug}-{other}.html">' for other in L)
 return f'''<!doctype html>
<html lang="{l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | YPARC</title><meta name="description" content="{e(description,quote=True)}"><link rel="canonical" href="https://painclinic.am/{slug}-{l}.html">{alternates}<link rel="stylesheet" href="conditions.css"></head>
<body><a class="skip" href="#main">{e(t['toc'])}</a><header><div class="wrap header"><a class="brand" href="{home}"><img src="yparc-logo.png" width="150" height="80" alt="YPARC"></a><nav aria-label="{e(t['home'])}"><a href="{home}">{t['home']}</a><a href="about-{l}.html">{t['about']}</a><a href="conditions-{l}.html">{t['conditions']}</a><a href="patient-{l}.html">{t['patient']}</a></nav><div class="actions"><div class="languages" aria-label="Language">{languages}</div><a class="button" href="booking-{l}.html">{t['booking']}</a></div></div></header>
<main id="main">{body}</main><footer><div class="wrap footer"><div><strong>YPARC</strong><p>Yerevan Pain &amp; Rehabilitation Clinic</p><p>{t['address']}</p></div><div><strong>{t['contact']}</strong><p><a href="tel:+37491092123">+374 91 092123</a></p><p><a href="mailto:info@painclinicyerevan.am">info@painclinicyerevan.am</a></p><a href="booking-{l}.html">{t['booking']}</a></div></div><div class="wrap legal">© 2026 YPARC</div></footer></body></html>'''
def detail(x,l):
 t=L[l];slug=x['slug'];title=x['title'][l]
 image=''
 if x.get('image'):
  im=x['image'];alt={'neck':['Պարանոցի հատվածին ձեռքը դրած մարդ','Person resting a hand on the neck','Человек с рукой на шее'],'knee':['Նստած մարդ՝ ձեռքը ծնկի վրա','Seated person with a hand on the knee','Сидящий человек с рукой на колене'],'wrist':['Դաստակը ձեռքով աջակցող մարդ','Person gently supporting a wrist','Человек мягко поддерживает запястье']}[im][{'hy':0,'en':1,'ru':2}[l]]
  image=f'<figure><img src="images/{im}-pain-editorial.webp" width="1536" height="1024" alt="{alt}" fetchpriority="high"><figcaption>{t["caption"]}</figcaption></figure>'
 toc=''.join(f'<a href="#{k}">{t[k]}</a>' for k in ['symptoms','assessment','care','urgent'])
 symptoms=''.join(f'<li>{e(s)}</li>' for s in x['symptoms'][l])
 note=f'<aside class="note"><strong>{t["note"]}</strong><p>{e(x["note"][l])}</p></aside>' if x.get('note') else ''
 related=''.join(link(s,l) for s in x['related'])
 source=f'<p class="source">{t["read"]}: <a href="{SOURCES[slug]}">NHS</a></p>' if slug in SOURCES else ''
 body=f'''<section class="hero"><div class="wrap"><div class="breadcrumb"><a href="conditions-{l}.html">{t['conditions']}</a> / {e(group(x['group'],l))}</div><div class="hero-grid {'with-image' if image else ''}"><div><p class="eyebrow">{e(group(x['group'],l))}</p><h1>{e(title)}</h1><p class="intro">{e(x['intro'][l])}</p><a class="button" href="booking-{l}.html">{t['booking']}</a></div>{image}</div></div></section>
<div class="wrap article-layout"><aside class="contents"><strong>{t['toc']}</strong>{toc}</aside><article><section id="symptoms"><span class="number">01</span><h2>{t['symptoms']}</h2><ul class="symptoms">{symptoms}</ul></section><section id="assessment"><span class="number">02</span><h2>{t['assessment']}</h2><p>{e(x['assessment'][l])}</p></section><section id="care"><span class="number">03</span><h2>{t['care']}</h2><p>{e(x['care'][l])}</p>{note}</section><section id="urgent" class="urgent"><h2>{t['urgent']}</h2><p>{WARN[x['group']][{'hy':0,'en':1,'ru':2}[l]]}</p></section><section class="related"><h2>{t['related']}</h2><div>{related}</div></section>{source}<p class="disclaimer">{t['disclaimer']}</p></article></div>'''
 return shell(slug,l,title,x['intro'][l],body)
def catalogue(l):
 t=L[l];sections='';filters=''
 for g in GROUPS:
  filters+=f'<a href="#group-{g}">{e(group(g,l))}</a>'
  cards=''.join(f'<a class="topic" href="{x["slug"]}-{l}.html" data-title="{e(x["title"][l].lower(),quote=True)}"><h3>{e(x["title"][l])}</h3><p>{e(x["intro"][l])}</p><span aria-hidden="true">↗</span></a>' for x in D if x['group']==g)
  sections+=f'<section class="topic-group" id="group-{g}"><h2>{e(group(g,l))}</h2><div class="cards">{cards}</div></section>'
 body=f'''<section class="hero"><div class="wrap"><p class="eyebrow">YPARC · 47</p><h1>{t['conditions']}</h1><p class="intro">{t['intro']}</p></div></section><div class="wrap catalogue"><label class="search-label" for="topic-search">{t['search']}</label><input id="topic-search" type="search" placeholder="{t['search']}" autocomplete="off"><nav class="category-nav" aria-label="{t['conditions']}">{filters}</nav><p id="search-status" role="status" aria-live="polite"></p><p id="no-results" hidden>{t['empty']}</p>{sections}<p class="disclaimer">{t['disclaimer']}</p></div><script src="conditions-search.js" defer></script>'''
 return shell('conditions',l,t['conditions'],t['intro'],body)
for l in L:
 for x in D: (R/f'{x["slug"]}-{l}.html').write_text(detail(x,l))
 (R/f'conditions-{l}.html').write_text(catalogue(l))
print(f'Rendered {len(D)} topic pages and directory in {len(L)} languages.')
